version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Install dependencies for the client
      - cd client
      - npm install
      # Install dependencies for the server
      - cd ../server  # Go back to the root, then into the server directory
      - npm install
      # Go back to root directory, after installations
      - cd ../
  build:
    commands:
      - echo "Building..."
      # Build the client
      - cd client
      - npm run build
      # Build the server (if applicable - often not needed for Node.js backends)
      - cd ../server
      - npm run build  # Or any other build command, e.g., tsc, webpack
      - cd ../
  post_build:
    commands:
      - echo "Post-build tasks..."
      # Example: Deploy the client to S3
      # - cd client/build
      # - aws s3 sync . s3://your-s3-bucket